### ISSUE TITLE
🚀 Feature: Redesign of the landing page

### ISSUE THREAD

**Issue by iamoghenerukevwe** [traceloop/jest-opentelemetry#32]
### 🔖 Feature description

Hi, in going through YCombinator's recent OS projects, I stumbled across traceloop, I landed on your site and I feel some changes could be effected to give it more life or make it look more active.

### 🎤 Why is this feature needed ?

It is paramount that there is a revamp of the landing page  as I've observed that you've just crossed 100 stars on Github and more and more people are going to visit the landing page, it needs to look like an active project.

### ✌️ How do you aim to achieve this?

This is my first foray into open-source so pardon me for any errors in my convention. I've created a design file and I'm willing to customize and effect changes. I can also convert that to live code using Next.js, all I need is approval or consent from the team.

![Dark](https://user-images.githubusercontent.com/50581464/221233389-174ab4e7-a985-4b32-9724-fb329d4d2436.png)
![Light](https://user-images.githubusercontent.com/50581464/221233436-ce38b38f-a4fd-4e61-858c-18234f84d34c.png)

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by nirga** [comment]
Hey! Thanks for taking the time to do this! Unfortunately our website isn't open source at the moment so we won't be able to accept your contribution. We do work on revamping our homepage so would to hear what you think after it's live in the next couple of days.

We'll be more than happy to support any contributions in this repo! We have lots of [test types that we plan to write](https://docs.traceloop.dev/jest-otel/syntax/overview).

**Comment by iamoghenerukevwe** [comment]
That's fine
